version: '3.8'

services:
  # 1) Teleport daemon (followed the user's example run command)
  teleport-daemon:
    image: public.ecr.aws/gravitational/teleport-distroless-debug:17.5.4
    container_name: teleport-daemon
    networks:
      - teleport-net
    env_file:
      - .env
    volumes:
      - ./teleport-daemon/config:/etc/teleport
      - ./teleport-daemon/data:/var/lib/teleport
      - ./teleport-daemon/keys:/etc/keys:ro
    ports:
      - "3025:3025"
      - "3080:3080"
    entrypoint: [ "teleport", "start", "--config=/etc/teleport/teleport.yaml" ]

  # 2) Backend - build from repo and run (uses the provided Dockerfile)
  backend:
    build:
      context: ./4th-security-Jarvis-BE
      dockerfile: Dockerfile
    image: backend:latest
    depends_on:
      - teleport-daemon
    networks:
      - teleport-net
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./teleport-daemon/keys:/etc/letsencrypt:ro
      - ./teleport-daemon/data:/var/lib/teleport
      - tbot-certs-volume:/opt/machine-id
      - ./4th-security-Jarvis-BE/identityDir:/opt

  # 3) Frontend - multi-stage build (build then serve with nginx)
  frontend:
    build:
      context: ./4th-security-Jarvis-FE
      dockerfile: Dockerfile
    image: frontend:latest
    depends_on:
      - backend
    networks:
      - teleport-net
    ports:
      - "3000:80"
    volumes:
      - ./teleport-daemon/keys:/etc/keys:ro

  # 4) ELK stack and event handler
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - teleport-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.18.1
    volumes:
      - ./logstash:/usr/share/logstash
      - ./plugin:/home
    networks:
      - teleport-net
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.1
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./teleport-daemon/keys:/etc/keys:ro
    networks:
      - teleport-net
    depends_on:
      - elasticsearch

  tp-event-handler:
    image: public.ecr.aws/gravitational/teleport-plugin-event-handler:17.7.1
    volumes:
      - ./plugin:/opt/teleport-plugin
      - tbot-certs-volume:/opt/teleport-plugin/identity:ro
    working_dir: /opt/teleport-plugin
    networks:
      - teleport-net
    depends_on:
      - logstash
    command: [ "start", "--config=teleport-event-handler.toml" ]

volumes:
  esdata:
  tbot-certs-volume:


networks:
  teleport-net:
    driver: bridge
