kind: role
metadata:
  name: api-impersonator
  revision: fcadb413-86cc-4d02-b18c-92a9cf6d291e
spec:
  allow:
    impersonate:
      roles:
      - '*'
      users:
      - '*'
    logins:
    - root
    node_labels:
      '*': '*'
    rules:
    - resources:
      - session_tracker
      verbs:
      - list
      - read
    - resources:
      - role
      verbs:
      - read
      - list
      - create
      - update
      - delete
    - resources:
      - user
      verbs:
      - read
      - list
      - create
      - update
      - delete
    - resources:
      - node
      verbs:
      - read
      - list
      - create
      - update
      - delete
    - resources:
      - app
      - db
      - kube_cluster
      verbs:
      - read
      - list
    - resources:
      - session
      - event
      verbs:
      - read
      - list
    - resources:
      - token
      verbs:
      - read
      - list
      - create
      - update
      - delete
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v5
